### ISSUE TITLE
Widget Organization & Class Structure

### ISSUE THREAD

**Issue by celloexpressions** [xwp/wp-core-media-widgets#1]
Since all media controls will have a shared set of code (and UI) to handle the media modal and the widget frame (title, caption, filters, etc.), there should be a parent class with the base functionality and child classes for the specific widgets. This would largely echo the way that customize controls work. I'm not sure if this is currently possible with widgets, but it would seem like a prerequisite for building separate image/video/audio/document widgets to me. Duplicating that baseline media code seems like a no-go.

I also wonder whether building these as separate widgets could actually cause more issues in a block-based system, where these widgets have to be merged with shortcodes and new blocks if all of these things come together. That could cause major backwards-compatibility issues within the next few months. This also relates to a comment I brought up in the context of editor blocks: when adding a media-type block, any type of media would likely bring up the existing media modal, at which point a more specific type of media could be selected. Or, even better, you could upload (or select) any type of file, then when you insert it it becomes a more specific type of block automatically. Rather than having to select the exact type of content from a much larger list of blocks, it's done automatically, which becomes particularly useful once you get into types of files that we may not be thinking about, starting with PDFs or .zips and extending to a very broad array of potential file types. It also seems to align with the core philosophies of striving for simplicity and decisions, not options. That approach can and should be balanced with discoverability but I doubt that making users select very-specific block types from the beginning is the best approach (and that doesn't necessarily mean that there couldn't also be a distinct image block that's tied into the more generic functionality - these are all questions that need to be researched).

All of that to say, if we want to launch something in the very near future as a quick win, we should go back to the more flexible media widget case, and constrain functionality where it makes sense for now. If we're looking for a more forward-thinking or longer-term approach, we should probably work out the best actual block-based solution rather than coming up with a set of interim widgets that could cause more problems than they solve.

**Comment by westonruter** [comment]
> Since all media controls will have a shared set of code (and UI) to handle the media modal and the widget frame (title, caption, filters, etc.), there should be a parent class with the base functionality and child classes for the specific widgets. This would largely echo the way that customize controls work. I'm not sure if this is currently possible with widgets, but it would seem like a prerequisite for building separate image/video/audio/document widgets to me. Duplicating that baseline media code seems like a no-go.

If there is enough duplicated code, this can be done by implementing a `abstract` class at the PHP level that the different media type widgets inherit from.

> I also wonder whether building these as separate widgets could actually cause more issues in a block-based system, where these widgets have to be merged with shortcodes and new blocks if all of these things come together.

I'm not worried about this because we're just adding more widgets as they already exist today. Ultimately if there is a harmonization with shortcodes and content blocks (which there should) we will have to deal with widgets regardless. So I don't think we're introducing any additional problems by adding new widget types before content blocks are figured out: we'll have to cross the widgets bridge when we come to it anyway.

> if we want to launch something in the very near future as a quick win, we should go back to the more flexible media widget case, and constrain functionality where it makes sense for now.

I think we can do a better job at constraining functionality by making type-specific widgets. The interface and data model will be simpler for widgets being type-specific, since the different media types have different type-specific properties (e.g. videos have poster images). I don't imagine a user would normally add a media widget that has an image in it, and then decide they want to replace the image in that same widget with an audio player. To me it seems more naturally that users would expect to remove the widget for the type they are replacing and add the new widget of the specific type to take its place.

**Comment by celloexpressions** [comment]
Regarding widget structure organization, the current direction of editor blocks and the way that I use and have seen other (DIY) people use WordPress suggests that there are fundamental problems with the assumptions being made here, starting from the types of media that would be supported and how one would go about adding them. I'm not going to argue it further since this is apparently just how it's going to be. You would think that documented user research and testing would be a good way to inform such a decision, though.

Technically speaking, we definitely should have a common base to support any type of widget that uses the media library and stores an attachment ID. It should be possible for core or plugins to add additional media-type-specific widgets without reworking everything. There needs to be a "parent class" approach in both JS and PHP for this to work reasonably. This also seems like redundant work to what was done previously with the media customize controls - might it make more sense to explore integrations of controls into widgets, and also building out the widgets JS API prior to implementing the media widget(s) (as was done with the customize API)?

In terms of technical debt, this is moving beyond a "quick win" that should be considered for a minor release. If we're going to expand the scope and try to come up with something that's productive long term, it should be done right with APIs expanded to properly support it in an extensible way.

**Comment by westonruter** [comment]
I think that the widget architecture which has base media classes in PHP and JS address the concerns in this issue.
