### ISSUE TITLE
Remove autoplay setting from audio and video widgets

### ISSUE THREAD

**Issue by melchoyce** [xwp/wp-core-media-widgets#104]
Everyone hates autoplay. :) Let's remove it from the default widget options.

**Comment by westonruter** [comment]
This will require a media template change to add a class name to be able to target the `autoplay` checkbox to give `display:none`. A similar hack was done for the Link Type field; this needs to be part of the core merge.

**Comment by timmyc** [comment]
Alternatively we could just not output the `autoplay` setting on the widget render.  Kind of misleading though.

**Comment by timmyc** [comment]
On second thought, couldn't autoplay have some potential design purposes for videos... like header video?  I agree about audio, that is just annoying.

**Comment by melchoyce** [comment]
Yeah, but that's a separate feature — and intentionally strips out the sound from the video. The widget wouldn't (shouldn't) be used for headers.
