### ISSUE TITLE
Poster Image not Cleared on Video Change

### ISSUE THREAD

**Issue by timmyc** [xwp/wp-core-media-widgets#106]
When changing a video from an external url ( i.e. YouTube ) and selecting a video file from the media library instead, the old poster image from the YouTube video is persisted and still shown.

__Steps to Recreate__
- Add a new video widget
- Set the URL to a YouTube video
- Confirm the poster image is shown in the `renderPreview`
- Click "Change Video"
- Select a video file from the media library
- Note in the `renderPreview` the old poster image is shown from the YouTube video, but if you click play, the video file from the library is properly set.

**Comment by westonruter** [comment]
Agreed. I mentioned this in https://github.com/xwp/wp-core-media-widgets/issues/95#issuecomment-296382665

**Comment by timmyc** [comment]
So essentially we need to "reset" certain attributes on the `model` when `attachment_id` or `url` changes as a result of the media modal action, while other attributes like maybe `preload` or `loop` should be persisted during the change.

Or do we keep it simple and when the media changes, reset everything back to defaults?

**Comment by westonruter** [comment]
My first thought is that I think only certain attributes should be reset, not everything, as that could make it really annoying for the user to have their previous values change.
