### ISSUE TITLE
Test video widget on supported browsers and devices

### ISSUE THREAD

**Issue by melchoyce** [xwp/wp-core-media-widgets#114]
- [x] Full support back to IE11, partial back to IE8.
- [x] Firefox, Chrome, Safari: Current – 1.
- [x] iOS Safari: Current – 1.
- [x] Android browser: Current major.
- [x] Chrome/Android: Current.

Add comments below with relevant screenshots and which browsers/devices have been tested. Once done, check of the boxes.

**Comment by obenland** [comment]
Tested on Browserstack:
* IE 8 on Win 7
* IE 11 on Win 10
* iOS 6 on iPhone 6+
* Android 4.4 on HTC One M8
* Chrome on Galaxy S7
* Firefox 52 on Win 10
* Safari 5 on Win7
* Chrome on macOS

I could not find any issues that are not already trac'd.
