### ISSUE TITLE
Fetch poster image to use in control preview for external oEmbed videos

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-core-media-widgets#121]
See https://github.com/xwp/wp-core-media-widgets/pull/116#issuecomment-298728107

**Comment by timmyc** [comment]
@westonruter should we wait for https://core.trac.wordpress.org/ticket/40450 to land before adding this back in?

**Comment by westonruter** [comment]
@timmyc no, I think we should just use noembed.com for the moment while we wait.
