### ISSUE TITLE
Captioned images overflow sidebar

### ISSUE THREAD

**Issue by obenland** [xwp/wp-core-media-widgets#13]
Because captions get a hardcoded pixel width, they almost always overflow the sidebar. Fixing this would require changing the core shortcode to accept inline styles

**Comment by melchoyce** [comment]
Should we open a core ticket for this?

**Comment by obenland** [comment]
Maybe. I don't know, could be part of this plugin too

**Comment by melchoyce** [comment]
I feel like we don't have this problem in galleries, so it might be the plugin, not core.

**Comment by obenland** [comment]
I don't think galleries use the shortcode though, do they? I mean the easiest way to mitigate it would be to make the short code more flexible so that we can pass our own styles and override the fixed width.

**Comment by melchoyce** [comment]
> I don't think galleries use the shortcode though, do they?

¯\_(ツ)_/¯

> I mean the easiest way to mitigate it would be to make the short code more flexible so that we can pass our own styles and override the fixed width.

Sounds good to me 👍

**Comment by obenland** [comment]
I tested the caption shortcode with all twenty themes, the overflow issue is only present in Twenty Ten (which I had active when I noticed).
Twenty Ten sets a pixel max-wdith with an `!important` flag. 
Twenty Sixteen doesn't clear floats in widgets, which leads to broken layouts when inserting a floated image. Images are floated left by default.
