### ISSUE TITLE
Text Widget: why destroy tinymce instance?

### ISSUE THREAD

**Issue by mtias** [xwp/wp-core-media-widgets#132]
Wonder what's the reasoning for needing to destroy tinymce after widget updates. Also, it may be worth to move this block of code into a separate "prepareEditor" function or similar.

https://github.com/xwp/wp-core-media-widgets/blob/master/wp-admin/js/widgets/text-widgets.js#L60-L76

**Comment by westonruter** [comment]
To summarize the Slack conversation: https://wordpress.slack.com/archives/C0381N237/p1493995366929336

Two reasons for why the editor needs to be rebuilt: on the widgets admin screen, clicking the “Save” button results in the widgets JS destroying the old widget form and replacing it with the new form coming from the Ajax response. This has negative user experience implications, as the editor will “flicker” after saving and also if you were on the Text tab entering HTML, the Visual tab gets focus after hitting save.

The second reason, and this is true both on the widgets admin screen and the customizer alike: when re-ordering a widget in a sidebar, this results in the TinyMCE editor and its iframe being moved in the DOM, and when an iframe is moved in the DOM it gets reloaded and thus the TinyMCE editor is destroyed and has to to be rebuilt.

For the former case, on the widgets admin screen, we did actually come up with a solution to avoid having to re-build the editor by moving the fields outside of the container that the widgets JS replaces with new content from the server. I hesitated doing the same for the Text widget for fear of back-compat issues for plugins that extend the Text widget, but the UX issues now I see outweigh that.
