### ISSUE TITLE
Interactions with "automatically add paragraphs", visual, and autop

### ISSUE THREAD

**Issue by mtias** [xwp/wp-core-media-widgets#133]
Don't know what the ideal experience should be here, but it's odd that visual mode is not really "visual" unless you check the "automatically add paragraphs" checkbox.

![image](https://cloud.githubusercontent.com/assets/548849/25750963/c3784d9e-31b3-11e7-9cbb-8735fc937847.png)

This produces:

![image](https://cloud.githubusercontent.com/assets/548849/25751047/026145ba-31b4-11e7-8ddc-e4568f35cdfb.png)

Which is counter intuitive to what you expect by having used the WP editor.

**Comment by mtias** [comment]
Maybe if the box is unchecked we can default to "text" mode, and if you switch to visual we force paragraphs to be created? It seems the choice of going "visual" should force that setting.

**Comment by obenland** [comment]
Is that option mot obsolete now anyway?

**Comment by mtias** [comment]
In which sense?

**Comment by obenland** [comment]
In the sense that it now should work like in the post/page editor, no?

**Comment by westonruter** [comment]
@mtias that checkbox should not even be visible. It should have been eliminated. 

Here's what I see in the customizer:

![image](https://cloud.githubusercontent.com/assets/134745/25758029/c927cfd0-3181-11e7-8aad-dea1283aa116.png)

And on the widgets admin screen:

![image](https://cloud.githubusercontent.com/assets/134745/25758041/d263006a-3181-11e7-88fc-33c252d3ad46.png)

**Comment by timmyc** [comment]
I'm seeing the same as @westonruter above.  Is there any chance you might have another plugin installed @mtias that would be creating that checkbox?

**Comment by westonruter** [comment]
Please re-open if persists.

**Comment by mtias** [comment]
I don't know how I got into that state. It seems to have cleared now, but I'll reopen if I get it again.
