### ISSUE TITLE
Improve the volume tooltip styling and position

### ISSUE THREAD

**Issue by afercia** [xwp/wp-core-media-widgets#140]
Was wondering if this could be a good opportunity to improve the styling and positioning of the volume "tooltip".
Note: the tooltip doesn't appear in Chrome because `wp-mediaelement.css` should reset also `clip-path` on focus.

On Firefox and Safari:

<img width="464" alt="screen shot 2017-05-06 at 19 02 24" src="https://cloud.githubusercontent.com/assets/1682452/25774486/c285de06-328f-11e7-9e76-558f249293f5.png">
<img width="423" alt="screen shot 2017-05-06 at 19 03 24" src="https://cloud.githubusercontent.com/assets/1682452/25774485/c283ba68-328f-11e7-92ce-b7f30cec984e.png">
<img width="465" alt="screen shot 2017-05-06 at 19 03 36" src="https://cloud.githubusercontent.com/assets/1682452/25774487/c28a3bea-328f-11e7-82c4-12e44a9a761a.png">

**Comment by afercia** [comment]
In the admin, it would probably need some z-index:

<img width="466" alt="screen shot 2017-05-06 at 19 19 47" src="https://cloud.githubusercontent.com/assets/1682452/25774540/14caa204-3291-11e7-81e1-bcb12c657d60.png">

**Comment by westonruter** [comment]
@afercia is the z-index the only unique issue here? Or even, if using a core media control in the Customizer is the issue also present? This seems like it is an issue that should be addressed in a Trac ticket?

**Comment by afercia** [comment]
@westonruter I'd say both 🙂 

<img width="400" alt="screen shot 2017-05-08 at 00 27 16" src="https://cloud.githubusercontent.com/assets/1682452/25785607/4b5ef898-3385-11e7-8ceb-2e0f793ebc4b.png">

**Comment by westonruter** [comment]
@afercia what I mean is what needs to be fixed in the context of this feature and which needs to be fixed generally in core?

**Comment by westonruter** [comment]
How are you even getting that range slider popup to appear? I can't see it in Firefox. I only see the horizontal slider, and I can't see any tooltip in Firefox either. Is that provided by your accessibility tool?

In any case, PRs appreciated.

**Comment by timmyc** [comment]
I am unable to see the tooltips in Safari or Firefox - what are the steps to reproduce this @afercia ?

**Comment by afercia** [comment]
@timmyc just use the keyboard and tab through the player controls. In the screenshot above you can also see the blue outline around the volume bar, that mens it's focused. See also:
https://core.trac.wordpress.org/browser/trunk/src/wp-includes/js/mediaelement/wp-mediaelement.css?rev=40052#L45

<img width="994" alt="screen shot 2017-05-09 at 23 49 19" src="https://cloud.githubusercontent.com/assets/1682452/25874300/33c4f60e-3512-11e7-917d-81e7ab31b6d5.png">

If you're using a Mac, please also check this system preference:

![screen shot 2016-06-04 at 14 20 26](https://cloud.githubusercontent.com/assets/1682452/25874394/ace4aa20-3512-11e7-88b2-a1fe76246459.png)
