### ISSUE TITLE
Title attribute in Image widget

### ISSUE THREAD

**Issue by samikeijonen** [xwp/wp-core-media-widgets#143]
I think title attribute should not be output by default when using Image widget. 

It should work the same way as in post.

1. Add image in a post and there is no title attribute from the Title input field.
1. Edit the image and under Advanced Options >> Image Title Attribute you can add title attribute if needed (not sure should there ever be a reason to add title attribute anyways).

@afercia do you have opinion on this one?

**Comment by westonruter** [comment]
@samikeijonen @afercia like #146?

**Comment by afercia** [comment]
Yep the title attribute issue was already mentioned in #47, haven't had the time to have a look at #146 though.
