### ISSUE TITLE
Adding link doesn't refresh the widget

### ISSUE THREAD

**Issue by samikeijonen** [xwp/wp-core-media-widgets#144]
When adding a link in Text widget in most cases I don't see the widget refreshing and link doesn't show up in the preview.

I tested like this:

1. Add text widget.
1. Add some text.
1. Select a word and click Insert/Edit link button.
1. From there click Link options.
1. From there search and select page.
1. I don't see a link in the preview.

Screenshot:

<img width="1222" alt="No link in the preview" src="https://cloud.githubusercontent.com/assets/1820415/25779396/5ff4a00c-331f-11e7-84b6-8ea9dfff8de9.png">

**Comment by westonruter** [comment]
I bet it is because the link editor is mutating the DOM in a way that TinyMCE isn't picking up a `change` event.

**Comment by westonruter** [comment]
Indeed this is the case. I just added a link to an existing saved widget and no change was picked up:

![image](https://cloud.githubusercontent.com/assets/134745/25816879/6926eda4-33da-11e7-86af-965ff8b3d43c.png)

**Comment by westonruter** [comment]
@samikeijonen if you can test #147 that would be helpful.

**Comment by samikeijonen** [comment]
I'll test in a minute.

**Comment by samikeijonen** [comment]
Hmm I cloned this repo and in `master` branch I see JS errors: `Uncaught TypeError: Cannot read property 'initialized' of null at buildEditor (text-widgets.js:90)`. And now I can't open the text widget.

Is there something I'm missing when testing master branch? I used to test using the plugin version in .org.

**Comment by samikeijonen** [comment]
#147 solves the issue though!
