### ISSUE TITLE
Warning on WP_Widget_Media::display_media_state()

### ISSUE THREAD

**Issue by timmyc** [xwp/wp-core-media-widgets#159]
Testing the plugin out on a few different sites, and I encountered the following:

![media_library_ _haiku2_ _wordpress](https://cloud.githubusercontent.com/assets/22080/25865271/3ec6dec0-34a7-11e7-84e2-764e1c38911f.png)

Seen in the list view of the media library at `/wp-admin/upload.php?mode=list`

**Comment by westonruter** [comment]
@timmyc I can see that the `display_media_states` filter added the second `$post` parameter in `trunk` (4.8), so if wouldn't be available on 4.7.x. Is that what you're on?

**Comment by timmyc** [comment]
Indeed this was seen on a site running 4.7.x
