### ISSUE TITLE
Widgets added/removed using Appearance > Widgets did not reflect in Customizer

### ISSUE THREAD

**Issue by jasmussen** [xwp/wp-core-media-widgets#169]
Hi friends —  out of excitement I took the plugin for a spin on a fresh trunk vvv install using Twenty Seventeen. The widgets look great, and work great! Really dig it, I think people are going to love it. 

One quick issue —  in my test, which was using plugin version 0.1.0-20170510, any widget added or removed using Appearance > Widgets was completely ignored in Appearance > Customize > Widgets. The Twenty Seventeen starter content was present there, even if I had already removed it in Appearance > Widgets

Steps to reproduce:

- Open a fresh WordPress trunk install (or maybe unfresh, dunno)
- Open Appearance > Widgets
- Add or remove any widget
- Open Appearance > Customize > Widgets

Result: changes made in Appearance > Widgets did not reflect. 

Screenshots:

![widgets](https://cloud.githubusercontent.com/assets/1204802/25899459/404d8e12-3590-11e7-89ed-bcf6c9184c89.png)

![customizer](https://cloud.githubusercontent.com/assets/1204802/25899467/4586ef36-3590-11e7-89dc-05d201d12d78.png)

**Comment by westonruter** [comment]
It looks like you have found a bug with starter content that isn't related specifically to the widgets. If you Save & Publish once in the Customizer and then go to the widgets admin screen to make widget changes, do you then see those changes refected in the Customizer when it is opened?

**Comment by jasmussen** [comment]
Yes, saving and publishing in the customizer and then going back to widgets does as you suggest, and any changes from then on are "in sync", correct. But saving and publishing replaced all the widgets I'd made first, without even moving them to "inactive widgets".

**Comment by westonruter** [comment]
Yes, that would be expected since it (incorrectly) thinks it is still a `fresh_site`, and so it overrides existing widgets thinking that they are just the initial install content. So I think this is a core bug.

**Comment by westonruter** [comment]
Opened core ticket: https://core.trac.wordpress.org/ticket/40722

**Comment by jasmussen** [comment]
Thank you, excellent detective work!
