### ISSUE TITLE
Media widget placeholder box looks like a dropzone

### ISSUE THREAD

**Issue by jasmussen** [xwp/wp-core-media-widgets#170]
Let me first exclaim how much I love these new widgets. They look completely great, and work well too.

In the Image, Video and Audio widgets, there's a little dashed line box. This looks like an upload dropzone:

![drag drop doesn t work here but it looks like it should](https://cloud.githubusercontent.com/assets/1204802/25899517/75b92c00-3590-11e7-973b-f9fc60cd55a6.png)

But it's not an upload dropzone. 

Two ways to improve this:

- Make it a dropzone 🎉🚀 🤞
- Redesign it ever so slightly

Perhaps it's enough to make the dashed line solid, and the background some shade of gray so the box looks like a placeholder. I think it's the dashed lines that makes it feel like it follows a dropzone pattern.

**Comment by afercia** [comment]
See also https://core.trac.wordpress.org/ticket/34323 and a couple discussions on Slack #design linked in that ticket :)

**Comment by jasmussen** [comment]
Yaay, it's already on the radar!

**Comment by melchoyce** [comment]
I'm a +1 for this, but it has to happen in core, so I'm going to close. Can you add your feedback to that trac ticket, @jasmussen?

**Comment by melchoyce** [comment]
Oh, there's also this ticket I made specifically about turning it into a dropzone: https://core.trac.wordpress.org/ticket/35827

**Comment by jasmussen** [comment]
I trust your triage completely! Thanks for letting me "ask via ticket", and thanks for the links Mel and Andrea both!

**Comment by melchoyce** [comment]
The good thing is the media widgets are definitely exposing rough edges in core, that we can hopefully now prioritize :)
