### ISSUE TITLE
How can I add extra buttons to the Text Widget editor.

### ISSUE THREAD

**Issue by ivorpad** [xwp/wp-core-media-widgets#184]
I was looking in `class-wp-widget-text.php` but can't wrap my head around it. I want to add extra `mce_buttons` in the Visual Tab such as **align-left | align-center | align-right**. Any idea about how to accomplish this?

**Comment by westonruter** [comment]
This is documented in https://make.wordpress.org/core/2017/05/23/addition-of-tinymce-to-the-text-widget/
