### ISSUE TITLE
Add a background behind image widget images if they aren't full width

### ISSUE THREAD

**Issue by melchoyce** [xwp/wp-core-media-widgets#185]
## Before:

![without background](https://user-images.githubusercontent.com/2846578/29218760-d369e934-7e83-11e7-83ba-44c3446e5ead.png)

## After:

![with background](https://user-images.githubusercontent.com/2846578/29218763-d59f077a-7e83-11e7-9c94-c31d0eb59db2.png)

Background color is `#eee`

**Comment by westonruter** [comment]
@melchoyce I think this should be moved to Trac since the Image widget is already merged and so it's not so straightforward to patch it in feature plugin.

**Comment by melchoyce** [comment]
https://core.trac.wordpress.org/ticket/41630
