### ISSUE TITLE
Default to "custom URL" in the image widget

### ISSUE THREAD

**Issue by melchoyce** [xwp/wp-core-media-widgets#186]
## Before:

![image](https://user-images.githubusercontent.com/2846578/29218977-a88289aa-7e84-11e7-9503-3573798dcde1.png)

## After:

![image](https://user-images.githubusercontent.com/2846578/29218995-b7bf8f12-7e84-11e7-8db4-9396a7410fa6.png)

**Comment by westonruter** [comment]
@melchoyce I think this should be moved to Trac since the Image widget is already merged and so it's not so straightforward to patch it in feature plugin.

**Comment by melchoyce** [comment]
https://core.trac.wordpress.org/ticket/41629
