### ISSUE TITLE
Clicking empty gallery placeholder opens manage frame instead of select frame

### ISSUE THREAD

**Issue by joyously** [xwp/wp-core-media-widgets#192]
When I add the gallery widget to a sidebar, I click on "Add Media" or "No images selected" and it shows the modal window below. Note that this says "Edit Gallery" and it does not show any of the images in my Media Library. I was able to upload images (thinking that this test site didn't have any), and then I went to the Media Library in a separate tab to see that they were there. But so were a lot of other images! Why aren't these showing as a choice for display?

![gallery-widget-initial-view](https://user-images.githubusercontent.com/7957680/30707640-c1822b38-9ec1-11e7-9c58-2308c32fb11d.jpg)

**Comment by joemcgill** [comment]
Looks like the media frame is opening in the wrong state if we don't have any attachments.

**Comment by westonruter** [comment]
@joyously are you sure it's if you click _either_ “Add Media” or the placeholder “No images selected”? I am only able to reproduce the issue in the latter case.

**Comment by joyously** [comment]
After I wrote the issue, I tried it a couple more times. I think it's only on "No images selected". The problem is that "No images selected" is a link too soon. I think the first time, I put the widget in a sidebar and then refreshed the front end page to see if it showed anything when no images were chosen. It did not, and when I went back to admin, I deleted that one and added it again. So I think I lost track of when I clicked what.
If you try the Image widget, the "No images selected" is not a link, ever. But it is in the Gallery widget, and probably should not be.

**Comment by westonruter** [comment]
I'll open a PR for the fix to clicking on the placeholder to open the proper screen.

> If you try the Image widget, the "No images selected" is not a link, ever. But it is in the Gallery widget, and probably should not be.

I don't agree. It's a nice shortcut to be able to click on the placeholder or existing images.

**Comment by joyously** [comment]
Wouldn't it make sense for the Image widget and the Gallery widget to behave the same (whichever way is best) for clicking on the placeholder?

**Comment by westonruter** [comment]
Yes, the image widget should get the same behavior.

**Comment by joemcgill** [comment]
Great observation @joyously. I agree with @westonruter that we should update the image widget once this is fixed to make the behavior consistent.
