### ISSUE TITLE
Resizing of local video in accordion

### ISSUE THREAD

**Issue by modulbuero** [xwp/wp-core-media-widgets#194]
Hey guys,

on a clients website we use locally uploaded videos (m4v) with the Core Video Widget. The ones placed in an accordion show up extending over the containers border when revealed on click. Setting the max-width to 100% does help with the width, but then the aspect ratio is broken. Is there a js-function to execute after revealing? I was guessing 

`jQuery( window.wp.mediaelement.initialize );`

…but that didn't work. Any ideas?

Thanks!
Christian

**Comment by westonruter** [comment]
Try `wp.mediaelement.initialize()`. See https://github.com/WordPress/wordpress-develop/blob/5c8c480d22a0412bb6c10c5302696d9eb62a7447/src/wp-includes/js/customize-selective-refresh.js#L476-L483

However, it seems like you're saying the element is getting created, but just its dimensions aren't right. For that you may want to look at https://stackoverflow.com/a/20132689/93579

**Comment by modulbuero** [comment]
Hey, thanks. Triggering the Resize did work, the direct solutions accessing the wp.mediaelement did not:

`window.wp.mediaelement.setPlayerSize();
window.wp.mediaelement.setControlsSize();`

"Uncaught TypeError: window.wp.mediaelement.setPlayerSize is not a function"

But anyways, triggering resize is fine with me. Thanks a lot!
