### ISSUE TITLE
Image doesn't sit within widget container

### ISSUE THREAD

**Issue by maddisondesigns** [xwp/wp-core-media-widgets#24]
Just tried this new Image Widget on a custom theme, Twenty Seventeen and also on Twenty Twelve and got the same result after adding an image. The image doesn't sit nicely in the actual widget.

Here's Twenty Twelve - https://cl.ly/3z0n3x0j0n15

**Comment by westonruter** [comment]
@maddisondesigns thanks for the report. It seems that your install doesn't have the `medium` size, or the size is much larger than normal. Can you share the `src` URL for the `img`? On my local install I have a URL like `http://src.wordpress-develop.dev/wp-content/uploads/2017/03/15874805_559673229851_5759796263826048451_o-300x225.jpg`, note the `300x225` dimensions.

The underlying template in `\WP_Widget_Image::render_control_template_scripts()` is currently:

```html
<# if ( 'image' === data.attachment.type && data.attachment.sizes && data.attachment.sizes.medium ) { #>
	<img class="attachment-thumb" src="{{ data.attachment.sizes.medium.url }}" draggable="false" alt="" />
<# } else if ( 'image' === data.attachment.type && data.attachment.sizes && data.attachment.sizes.full ) { #>
	<img class="attachment-thumb" src="{{ data.attachment.sizes.full.url }}" draggable="false" alt="" />
<# } #>
```

So it seems on your system it may be falling back to the `full` size.

Some todos I see here:

- The image should have a `max-width:100%`.
- The image should be centered in the widget form if it is narrower than the container.
- Aside: There should be a fallthrough case where it uses `data.url` from the underlying model in case an an external image is used or there are no sizes. (There is an existing todo for this that can be handled elsewhere.)

**Comment by maddisondesigns** [comment]
I do have the Medium size configured in my settings. The width is set to 620px, which is not large by any means. - https://cl.ly/0x2N3D1r3720

The URL of the image in the actual Widget on the Widgets page, is:
`<img class="attachment-thumb" src="http://dev.wordpress-test.com/wp-content/uploads/2012/08/TheAvengers-620x445.jpg" draggable="false" alt="">`

So, the widget is displaying the Medium size for that image. The full size image is 890×640px.

This is the URL it produces on the front of the site:
`<img src="http://dev.wordpress-test.com/wp-content/uploads/2012/08/TheAvengers-620x445.jpg" class="image wp-image-1487 " alt="" title="TheAvengers" style="max-width: 100%; height: auto;" srcset="http://dev.wordpress-test.com/wp-content/uploads/2012/08/TheAvengers-620x445.jpg 620w, http://dev.wordpress-test.com/wp-content/uploads/2012/08/TheAvengers-624x448.jpg 624w, http://dev.wordpress-test.com/wp-content/uploads/2012/08/TheAvengers.jpg 890w" sizes="(max-width: 620px) 100vw, 620px" width="620" height="445">`

As you pointed out, it needs:
```
.media-widget-preview img {
    max-width: 100%;
}
```

**Comment by westonruter** [comment]
@maddisondesigns thanks for the helpful details. Please give #26 a try if possible.

**Comment by maddisondesigns** [comment]
I've just tried that updated `media-widgets.css` file and that's looking a lot better now.
https://cl.ly/3x3V2t3y1E0D

Thanks.
