### ISSUE TITLE
Open link in a new tab checkbox

### ISSUE THREAD

**Issue by maddisondesigns** [xwp/wp-core-media-widgets#25]
It would be nice if there was an _Open link in a new tab_ checkbox on the _Select Image_ dialog rather than having to select an image and then edit the image, just to select this checkbox. It makes for a cumbersome user experience.

i.e. on this screen: https://cl.ly/0I3l1U1a0l1n

**Comment by westonruter** [comment]
For now we've just been re-using existing media frames and their core templates. So the Attachment Display Settings are defined in this template: https://github.com/WordPress/wordpress-develop/blob/4.7.3/src/wp-includes/media-template.php#L604-L678

We'd have to somehow override the `AttachmentDisplay.prototype.template` when opening the frame, per: 
https://github.com/WordPress/wordpress-develop/blob/4.7.3/src/wp-includes/js/media/views/settings/attachment-display.js#L13-L15

However, there are many other display settings that are available in the edit frame which aren't available in the abbreviated display settings on the select frame, so I'm not sure if adding this one setting setting should be done while the others are left out.

**Comment by maddisondesigns** [comment]
Besides the `Open link in a new tab` checkbox, the only other options that aren't on that _Select image_ dialog (but are on the Edit frame) are the `Image Title Attribute`, `Image CSS Class`, `Link Rel` and `Link CSS Class` fields. I would argue that those 4 particular fields are very rarely, if ever, used, whereas the new tab checkbox is something that a lot of people use quite regularly.

Personally, I think that checkbox should be on that dialog permanently, so that it's available even when inserting an image into your standard Post/Page content.

**Comment by westonruter** [comment]
@maddisondesigns this might be something then to propose in a Trac ticket for the media manager generally rather than specifically for the image widget.

**Comment by maddisondesigns** [comment]
Yeah, that's fair enough. Happy for you to close this one then and I can raise a Trac ticket and see if anything happens with it. Thanks.

**Comment by westonruter** [comment]
Thanks for the good discussion.
