### ISSUE TITLE
"No image selected" needs styling

### ISSUE THREAD

**Issue by melchoyce** [xwp/wp-core-media-widgets#29]
This: 

<img src="https://cloud.githubusercontent.com/assets/2846578/24052554/44ddebec-0b0c-11e7-947f-a798b7b89526.png" width="50%">

Should look like this:

<img src="https://cloud.githubusercontent.com/assets/2846578/24052591/67151172-0b0c-11e7-843a-97015606cc69.png" width="50%">

Looks like it's a CSS specificity issue. The placeholder has the `.placeholder` class applied, but the placeholder style is actually more specific than that:

```
.customize-control .attachment-media-view .placeholder,
.customize-control-header .placeholder
```

**Comment by westonruter** [comment]
This needs to be implemented for the widgets admin screen as well.

Here's what it looks like:

![image](https://cloud.githubusercontent.com/assets/134745/24111295/3d8a7484-0d53-11e7-98a9-bffb49a80233.png)
