### ISSUE TITLE
Implement audio widget

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-core-media-widgets#31]
The `audio` widget was disabled with the refactor in #17, and the [`WP_Widget_Audio`](https://github.com/xwp/wp-core-media-widgets/blob/master/wp-includes/widgets/class-wp-widget-audio.php) class needs to be refactored to match what was done for the [`WP_Widget_Image`](https://github.com/xwp/wp-core-media-widgets/blob/master/wp-includes/widgets/class-wp-widget-image.php) class, including the creation of a Backbone View `AudioWidgetControl` and `AudioWidgetModel` according to [what was done for the image widget](https://github.com/xwp/wp-core-media-widgets/blob/master/wp-admin/js/widgets/media-image-widget.js).

See #32 for the same for video.

**Comment by melchoyce** [comment]
This is lower priority than video (#32), gallery (#62), and slideshow (#63).
