### ISSUE TITLE
Implement video widget

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-core-media-widgets#32]
The `video` widget was disabled with the refactor in #17, and the [`WP_Widget_Video`](https://github.com/xwp/wp-core-media-widgets/blob/master/wp-includes/widgets/class-wp-widget-video.php) class needs to be refactored to match what was done for the [`WP_Widget_Image`](https://github.com/xwp/wp-core-media-widgets/blob/master/wp-includes/widgets/class-wp-widget-image.php) class, including the creation of a Backbone View `VideoWidgetControl` and `VideoWidgetModel` according to [what was done for the image widget](https://github.com/xwp/wp-core-media-widgets/blob/master/wp-admin/js/widgets/media-image-widget.js).

See #31 for the same for audio.

**Comment by timmyc** [comment]
I was going to dive in on this one... do we have any designs for how the outputs of `render_media` for the front-end display and the `render_preview` should look?

**Comment by melchoyce** [comment]
It should use core's default video player design:

![image](https://cloud.githubusercontent.com/assets/2846578/24766091/06ee2a60-1ac8-11e7-9de8-6c67b5c9a480.png)

![image](https://cloud.githubusercontent.com/assets/2846578/24766112/1e23288e-1ac8-11e7-9d06-f8bd1c76850d.png)

**Comment by westonruter** [comment]
Take note of this comment here for some complications on custom styling of the video (and audio) elements: https://core.trac.wordpress.org/ticket/32417#comment:116

**Comment by melchoyce** [comment]
PS if any of y'all wanted to look at https://core.trac.wordpress.org/ticket/31139 too... ;) <3
