### ISSUE TITLE
Test image widget on supported browsers and devices

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-core-media-widgets#36]
- [x] Full support back to IE11, partial back to IE8.
- [x] Firefox, Chrome, Safari: Current – 1.
- [x] iOS Safari: Current – 1.
- [x] Android browser: Current major.
- [x] Chrome/Android: Current.

Add comments below with relevant screenshots and which browsers/devices have been tested. Once done, check of the boxes.

**Comment by timmyc** [comment]
IE8 Widget View:
![ie8_-_win7__running_](https://cloud.githubusercontent.com/assets/22080/24878946/f4901d72-1de9-11e7-83cd-bd0a917c3605.png)

Note "Select Image" button and "No Image selected" placeholder are both shown even when an image is selected.

Otherwise working as expected in IE8 with media library selections and adding via URL.

**Comment by timmyc** [comment]
@westonruter when you say "partial back to IE8" what exactly does that mean?  Should the issue of the Select Image and placeholder above be fixed?

**Comment by westonruter** [comment]
@timmyc “partial back to IE8” means it's functional but the styling may not be quite right.

It looks like the problem here is IE8's lack of support for `:not()` 😦 

So yeah, that needs to be fixed. This would be a good thing to fix while also fixing #66 and #61.

**Comment by timmyc** [comment]
Okay IE9 Results, I'm hitting a JS error with anything customizer related in general.  Wondering if someone else had a VM handy to test but, the following is triggered when simply adjusting the title on any widget ( even non-media widgets ):

![ie9_-_win7__running_](https://cloud.githubusercontent.com/assets/22080/24881448/a39ae402-1df2-11e7-872d-8772464d527a.png)

This also prevents any edits from happening within the medial modal as well - nothing saves once this exception occurs.

This is the line that is throwing the error: https://core.trac.wordpress.org/browser/trunk/src/wp-admin/js/customize-controls.js#L4780

Edits working as expected from the Widget manager.

**Comment by timmyc** [comment]
Perhaps the error is related to https://core.trac.wordpress.org/changeset/39686/trunk/src/wp-admin/js/customize-controls.js

**Comment by westonruter** [comment]
@timmyc youch! Good catch! I can see that the change there did not sufficiently check for IE9 compat. I think a change like this is needed:

```diff
--- src/wp-admin/js/customize-controls.js
+++ src/wp-admin/js/customize-controls.js
@@ -4762,6 +4762,12 @@
 			 */
 			populateChangesetUuidParam = function( isIncluded ) {
 				var urlParser, queryParams;
+
+				// Abort on IE9 which doesn't support history management.
+				if ( ! history.replaceState ) {
+					return;
+				}
+
 				urlParser = document.createElement( 'a' );
 				urlParser.href = location.href;
 				queryParams = api.utils.parseQueryString( urlParser.search.substr( 1 ) );
@@ -4780,11 +4786,9 @@
 				history.replaceState( {}, document.title, urlParser.href );
 			};
 
-			if ( history.replaceState ) {
-				changesetStatus.bind( function( newStatus ) {
-					populateChangesetUuidParam( '' !== newStatus && 'publish' !== newStatus );
-				} );
-			}
+			changesetStatus.bind( function( newStatus ) {
+				populateChangesetUuidParam( '' !== newStatus && 'publish' !== newStatus );
+			} );
 
 			// Expose states to the API.
 			api.state = state;
```

Could you test that and see if it fixes IE9 for you? If so, we can then create a new ticket for 4.7.4 and I'll commit the patch to fix the bug in `trunk`.

**Comment by timmyc** [comment]
👍  @westonruter  that diff LGTM, and indeed fixes the bug in IE9 for the issues I was experiencing in the customizer.

**Comment by westonruter** [comment]
@timmyc see https://core.trac.wordpress.org/ticket/40405

**Comment by westonruter** [comment]
> and indeed fixes the bug in IE9 for the issues I was experiencing in the customizer.

Fix has been committed to `trunk` in [r40405](https://core.trac.wordpress.org/changeset/40405).

**Comment by timmyc** [comment]
Firefox, Safari, Chrome all looking good in current and prior versions.

**Comment by timmyc** [comment]
iOS and Chrome on Android are working well - the media modal though is a bit obscured by the attachment details sidebar:

<img width="317" alt="glass_and_iphone_se_ _ios_10_1__14b72_" src="https://cloud.githubusercontent.com/assets/22080/24887083/3529a366-1e0e-11e7-951c-5a9ee8e5e98c.png">

<img width="279" alt="dashboard" src="https://cloud.githubusercontent.com/assets/22080/24887090/3c8cd182-1e0e-11e7-97ee-8af927082a66.png">

**Comment by Kasutan** [comment]
The widget is working fine on Firefox 52, Chrome 57 and Edge 38.
I noticed that some strings are not translated (tested on a French-language install).
Sorry if this normal at this stage, I'm not familiar with the Wordpress development workflow.

![2017-04-16 13_08_47](https://cloud.githubusercontent.com/assets/18510925/25070867/86b51e46-22a9-11e7-9697-1b4607476b2a.jpg)
![2017-04-16 13_08_40](https://cloud.githubusercontent.com/assets/18510925/25070868/878f7712-22a9-11e7-99cf-137781be2062.jpg)

**Comment by obenland** [comment]
In desktop Safari the video player doesn't show a default image:

![screen shot 2017-04-24 at 10 59 51 am](https://cloud.githubusercontent.com/assets/1398304/25351328/31918d3e-28dd-11e7-8974-521d91cb0d57.png)

Should we just add a black background to the `video` element in the control preview?
[EDIT]: This only applies when there is no preview image selected of course

**Comment by obenland** [comment]
```css
.media-widget-buttons .button {
	margin: 8px 0 0 8px;
	width: auto;
}
```
doesn't seem to apply on small screens, leading to a missing margin between media and buttons:

![screen shot 2017-04-24 at 11 49 21 am](https://cloud.githubusercontent.com/assets/1398304/25353459/1d4a0822-28e4-11e7-8857-65ad4cc0362c.png)

**Comment by obenland** [comment]
In the image widget, it doesn't look like we're currently honoring "Link to" settings. It doesn't matter what I select, once I open the edit screen it's back to "none".

**Comment by timmyc** [comment]
> In the image widget, it doesn't look like we're currently honoring "Link to" settings. It doesn't matter what I select, once I open the edit screen it's back to "none".

I can't seem to re-create this issue.  I tried using a new image widget and setting link to as a custom URL and it worked.  Likewise with editing an existing image widget.

**Comment by obenland** [comment]
> I can't seem to re-create this issue. I tried using a new image widget and setting link to as a custom URL and it worked. Likewise with editing an existing image widget.

I actually only tested it with attachment and file links. It maybe that the edit screen just doesn't pick up the settings then? I've not investigated deeply so far

**Comment by melchoyce** [comment]
> Should we just add a black background to the video element in the control preview?
> [EDIT]: This only applies when there is no preview image selected of course

Yes 👍

**Comment by obenland** [comment]
Fixed.
