### ISSUE TITLE
Image widget buttons and flexbox

### ISSUE THREAD

**Issue by afercia** [xwp/wp-core-media-widgets#49]
A few issues quickly discussed on Slack about buttons and flexbox, maybe something to consider:
- the image widget buttons use flexbox; while the Customizer has dropped support for old IEs, the widgets screen hasn't
- it would be the first time flexbox is used in core (by core I mean not the customizer), maybe this should be discussed with the project leads, namely Helen :slightly_smiling_face:
- longer translations of the buttons may break everything, see screenshot below (`flex-wrap: wrap` plus some adjustments could help here but I'm not sure that would be the desired effect)

<img width="561" alt="screen shot 2017-04-05 at 23 18 00" src="https://cloud.githubusercontent.com/assets/1682452/24727718/5df24376-1a57-11e7-92f1-0d3bfb46bf45.png">

See also https://core.trac.wordpress.org/ticket/40220

**Comment by westonruter** [comment]
See also #15

**Comment by timmyc** [comment]
Some prior conversation on the topic [here](https://github.com/xwp/wp-core-media-widgets/pull/23#issuecomment-287899483) also.
