### ISSUE TITLE
Add button to edit media attributes in appropriate modal

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-core-media-widgets#6]
Upon selecting a media item, there should be a button that appears for changing the media:

<img width="285" alt="proposed-media-widget-edit-media-button 1" src="https://cloud.githubusercontent.com/assets/134745/23729999/e20f7a10-0419-11e7-8d8c-f67777cd6df1.png">

Clicking the item should open the relevant modal for editing that media item's attributes:

<img width="749" alt="modal-modal-edit-image-attachment-display-settings" src="https://cloud.githubusercontent.com/assets/134745/23730012/f6ad9128-0419-11e7-8b19-21479da8f049.png">

See more at https://core.trac.wordpress.org/ticket/32417#comment:136

**Comment by westonruter** [comment]
@adamsilverstein as [noted in Slack](https://wordpress.slack.com/archives/core-customize/p1488824781028023), if you could comment with a code snippet showing how to invoke the modal with a supplied state, and then show how to receive back the state attributes that are modified within the modal, that would be very helpful.

**Comment by adamsilverstein** [comment]
@westonruter I took a first pass at this in https://github.com/xwp/wp-core-media-widgets/pull/11
