### ISSUE TITLE
When image is deleted, only show 'Select Image' link

### ISSUE THREAD

**Issue by adamsilverstein** [xwp/wp-core-media-widgets#66]
When I use an image for the widget from my media library and later delete it, the widget interface correctly shows that the image is missing:

![](https://cl.ly/0e3u1v0C1733/Image%202017-04-10%20at%203.15.25%20PM.png)

The buttons below the image are incorrect, it should only show 'Select Image' as in the default state of the image when no image is selected:

![](https://d3vv6lp55qjaqc.cloudfront.net/items/1U0g3527312n0O1q0o2X/Widgets__developwordpress__WordPress_2017-04-10_15-18-09.jpg?X-CloudApp-Visitor-Id=1371633)

**Comment by westonruter** [comment]
Good catch. The issue is that right now it is only considering `MediaWidgetControl#isSelected` for whether to decide which buttons to show. It should also be considering `MediaWidgetControl#model.get( 'error' )`

**Comment by obenland** [comment]
> It should also be considering MediaWidgetControl#model.get( 'error' )

We currently only set the error in `selectedAttachment`, not the model. Should we switch that over?

**Comment by westonruter** [comment]
@obenland Humm. Perhaps. The only caveat there is that the `model` is normally representing the exact instance data. I suppose we could add new fields to it, since they wouldn't get synced back to the server since they are not among the schema.
