### ISSUE TITLE
Reordering widgets lost image preview in control

### ISSUE THREAD

**Issue by melchoyce** [xwp/wp-core-media-widgets#72]
<img width="1314" alt="screen shot 2017-04-11 at 11 21 41 am" src="https://cloud.githubusercontent.com/assets/2846578/24916765/1ae221b8-1ea9-11e7-99d5-9b1df39add79.png">

I reordered my widgets a couple times and then realized my preview disappeared.

**Comment by melchoyce** [comment]
Actually, maybe it's the master branch of the widget itself. I tried adding a new widget and it's also not previewing.

**Comment by westonruter** [comment]
@melchoyce You had an image being previewed in:

![image](https://cloud.githubusercontent.com/assets/134745/24918002/b7311878-1e93-11e7-91a5-182535afa848.png)

But then when you re-ordered it disappeared?

**Comment by melchoyce** [comment]
That's the thing — now I don't even know if it was there in the first place.

**Comment by westonruter** [comment]
It's strange that the Edit and Change buttons are both being shown even though there is “No image selected”.

**Comment by melchoyce** [comment]
Yeah, and there is an image showing up in my site preview.

**Comment by melchoyce** [comment]
Also, this is the nightly version of the plugin (or whatever's in the plugin repo), not trunk.

**Comment by westonruter** [comment]
@melchoyce have you been able to replicate the issue? I've not been able to make it happen. 

In any case, #73 may fix any underlying issue for rendering.

**Comment by melchoyce** [comment]
Can't reproduce anymore in master or the latest nightly, so I'm going to close.
