### ISSUE TITLE
Attached image preview flash

### ISSUE THREAD

**Issue by obenland** [xwp/wp-core-media-widgets#74]
![ezgif-2-dc989101e0](https://cloud.githubusercontent.com/assets/1398304/24964469/336010da-1f56-11e7-86ca-51ee7f957865.gif)

When previewing an attachment image in the widget preview and the selected size is not the full size, there is a flash of the selected image before the full attachment object has loaded and the image is replaced with its full size.

Should we wait showing a preview of the image until the attachment object has loaded?
Should the image size in the preview be a medium, like the default widget image size, rather than full?

**Comment by timmyc** [comment]
@obenland what are the steps to reproduce this - I can't seem to trigger it myself.

**Comment by obenland** [comment]
To reproduce:

1. Set an image and select thumbnail size.
1. Save the widget/customizer preview.
1. Reload.
1. Expand widget toggle.

**Comment by westonruter** [comment]
> Should the image size in the preview be a medium, like the default widget image size, rather than full?

Yes, if the `medium` size is available, it should be shown instead of `full`. This is currently being done in the media control actually, but I seem to have missed it in the template for the image control. See https://github.com/WordPress/wordpress-develop/blob/5fcfb9b247474e98a5deaa6f04781f3e99583094/src/wp-includes/customize/class-wp-customize-media-control.php#L159-L160

**Comment by westonruter** [comment]
> When previewing an attachment image in the widget preview and the selected size is not the full size, there is a flash of the selected image before the full attachment object has loaded and the image is replaced with its full size. ¶ Should we wait showing a preview of the image until the attachment object has loaded?

The reason this is happening is that we're currently storing the selected image size URL in the model's `url` attribute. If the attachment is not loaded yet, then it essentially falls-back to the `url` for preview in the control and also in `\WP_Widget_Media_Image::render_media()`.

In the control preview template (`\WP_Widget_Media_Image::render_control_template_scripts()`), this is the problematic line:

```html
<img class="attachment-thumb" src="{{ data.attachment_id && data.attachment.url ? data.attachment.url : data.url }}" draggable="false" alt="{{ data.alt }}" <# if ( ! data.alt ) { #> aria-describedby="{{ describedById }}" <# } #> />
```

So perhaps when `data.attachment_id && ! data.attachment.url` the template should display a spinner instead? Or perhaps we could continue to show the current cached image `url` but with `opacity:0.5` to indicate it is still loading?
