### ISSUE TITLE
Attachment details show before image is selected

### ISSUE THREAD

**Issue by melchoyce** [xwp/wp-core-media-widgets#75]
<img width="1316" alt="screen shot 2017-04-12 at 11 37 18 am" src="https://cloud.githubusercontent.com/assets/2846578/24966254/6ba895de-1f74-11e7-80d5-b74372f1abe4.png">

You can see here that I don't have an image selected yet, but the attachment details are showing up anyway (empty)

**Comment by timmyc** [comment]
Related https://github.com/xwp/wp-core-media-widgets/issues/36#issuecomment-293110934
