### ISSUE TITLE
Allow the widgets to be overridden or disabled or to be filtered

### ISSUE THREAD

**Issue by eric-mathison** [xwp/wp-core-media-widgets#79]
I have implemented my own version of an Image Widget and it has such capabilities that allow a user to set specific details for each image that override the media gallery. Also added is the ability to add a specific url link, proper rel, custom sizing, and custom classes. This comes in handy when targeting specific user actions. 

It would be great that these core widgets could be disabled / overridden so they do not conflict or if the core widgets allow for custom filtering / adding custom fields such like this one. 

![image](https://cloud.githubusercontent.com/assets/7695760/24986510/4e5bc87e-1fc0-11e7-97ac-3c2fbadeeab2.png)

**Comment by westonruter** [comment]
@eric-mathison I think what you are describing is already implemented in the plugin. The “Edit Image” button here:

<img src="https://cloud.githubusercontent.com/assets/134745/24987186/5bc8944a-1fb3-11e7-852e-0a6e95846517.png" width=300>

Opens this modal, where all of the fields can be modified from what is stored in the underlying attachment:

![image](https://cloud.githubusercontent.com/assets/134745/24987204/7ab5a564-1fb3-11e7-89c7-b487e5b32c6d.png)

Are you describing something else?

**Comment by eric-mathison** [comment]
Are those independent from the media gallery? If so, that should work. I didn't see the modal screenshots.

**Comment by westonruter** [comment]
Yes, once you have selected an attachment you can then modify the fields independent of what is in the media library. Please give the plugin a spin.
