### ISSUE TITLE
Update widget descripton

### ISSUE THREAD

**Issue by melchoyce** [xwp/wp-core-media-widgets#81]
From:

> Displays an image file.

To: 

> Displays an image.

Because we're not displaying the file, we're displaying the image :)

**Comment by westonruter** [comment]
@melchoyce should it be more descriptive, like “Displays an image from the media library or from an external source.”? Though I guess this description would be longer than normal.

![image](https://cloud.githubusercontent.com/assets/134745/25019032/08f377cc-203e-11e7-8f29-c9323a05f69d.png)

**Comment by melchoyce** [comment]
I think we can keep it short :)
