### ISSUE TITLE
Handle height/width for videos

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-core-media-widgets#93]
There is no `height` or `width` fields when selecting or editing a video in the media manager. This is a challenge. The `video` shortcode defaults the width to `640` and the height as `360`. When MediaElement.js initializes, it resizes the video to fit inside of its container scaled, but if MediaElement.js is disabled to let the browser natively render the video player (via plugin `add_filter( 'wp_video_shortcode_library', '__return_empty_string' );`), the widget overflows the container:

![image](https://cloud.githubusercontent.com/assets/134745/25251790/597e8b1e-25cf-11e7-9fbd-ca8b9eaa2701.png)

If a `max-width:100%` is hacked onto the video container element, and the `height` attribute is removed as follows:

```diff
diff --git a/wp-includes/widgets/class-wp-widget-media-video.php b/wp-includes/widgets/class-wp-widget-media-video.php
index f772817..dfc82f7 100644
--- a/wp-includes/widgets/class-wp-widget-media-video.php
+++ b/wp-includes/widgets/class-wp-widget-media-video.php
@@ -135,6 +135,8 @@ class WP_Widget_Media_Video extends WP_Widget_Media {
 			return;
 		}
 
+		add_filter( 'wp_video_shortcode', array( $this, 'inject_video_max_width_style' ) );
+
 		echo wp_video_shortcode(
 			array_merge(
 				$instance,
@@ -142,6 +144,20 @@ class WP_Widget_Media_Video extends WP_Widget_Media {
 			),
 			$instance['content']
 		);
+
+		remove_filter( 'wp_video_shortcode', array( $this, 'inject_video_max_width_style' ) );
+	}
+
+	/**
+	 * Inject max-width and remove height.
+	 *
+	 * @param string $html Video shortcode HTML output.
+	 * @returns string HTML Output.
+	 */
+	public function inject_video_max_width_style( $html ) {
+		$html = preg_replace( '/\bheight="\d+"/', '', $html );
+		$html = str_replace( 'style="', 'style="max-width:100%;', $html );
+		return $html;
 	}
 
 	/**
```

The result is better for the native `video` element: 

![image](https://cloud.githubusercontent.com/assets/134745/25251846/98be1c0e-25cf-11e7-83d5-f7eaf3da45ae.png)

However, when MediaElement.js is re-enabled then the video displayed shorter than the native player:

![image](https://cloud.githubusercontent.com/assets/134745/25251909/e76d52fc-25cf-11e7-9f7b-0864882fa6ad.png)

Upon playing, however, it then resizes dynamically to have the proper height for the video.

**Comment by kopepasah** [comment]
Since we have the width and height of the video before it is rendered on the page, we can use PHP to calculate a padding we can add to the top of the `.wp-video` class and add a small amount of styles to accommodate for the changes.

We would only want to do this when `MediaElement.js` is not used and should not affect the output when it (`MediaElement.js`) is enabled again. 

Alternatively, we can also do this post-render with JavaScript (but that seems unnecessary since we already have the dimensions).

As a plus, this would also make the `video` responsive in the process. 🤓

**Comment by westonruter** [comment]
@kopepasah do we have the width and height of the video? I don't think we do and that's the root of the problem here. There's no utility in WordPress for obtaining the dimensions of an uploaded video as far as I know. That being said, an oEmbed response _will_ include the width/height so we can actually add the `width`/`height` to the model props. But, we don't know the dimensions of the resulting destination where the video is going to be placed. This is why in the first screenshot you can see the video is overflowing the sidebar container. So that's why I was thinking of some `max-width` style, but this won't preserve the original aspect ratio when a `height` is also defined.

**Comment by kopepasah** [comment]
@westonruter I should have wrote, "Since we have the width and height of the embed". We can use those fit the video within its container, as described above.

**Comment by westonruter** [comment]
@kopepasah but I don't think we have the width and height of the embed.

**Comment by melchoyce** [comment]
Related: https://core.trac.wordpress.org/ticket/31139

**Comment by melchoyce** [comment]
What if the video always had a height of 253 x 142 (scaled down from 512 x 288 to fit the customizer sizebar)? Anything 4:3, or using non-standard dimensions, can have black bars around the edges.

**Comment by westonruter** [comment]
The problem is fitting a video in the frontend sidebar, not the customizer controls pane. I think the combination of #124 and #116 (changing `preload` to `metadata`) will resolve the issue mostly.

**Comment by westonruter** [comment]
This is still not working right for external hosted embeds. 

Vimeo:

![image](https://cloud.githubusercontent.com/assets/134745/25733983/66aa1214-3113-11e7-8848-b8b2240a0d58.png)

YouTube:

![image](https://cloud.githubusercontent.com/assets/134745/25733999/9f837418-3113-11e7-9e84-629a378bfa72.png)

**Comment by kopepasah** [comment]
@westonruter sorry for the delayed reply. 

I am still getting an overflow in the `<video>` element. Was your commits supposed to address this element as well?

**Comment by westonruter** [comment]
@kopepasah I'm not getting overflow anymore. Where do you see it?

**Comment by westonruter** [comment]
See also `padding-bottom` hack in https://github.com/WordPress/gutenberg/pull/721

**Comment by kopepasah** [comment]
@westonruter my mistake, this is working as expected.
