### ISSUE TITLE
Ensure widget is still registered at running hook

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-core-media-widgets#98]
Since hooks are added in the constructor (not ideal) when the hook runs it should ideally check to make sure the widget is still enqueued.

**Comment by obenland** [comment]
We could move the hooks to `_register()` so they'd only get added when the widget does get registered. 

Unfortunately `WP_Widget_Factory` doesn't notify a widget when it gets unregistered and there is also no action that fires in that event, so we can't do any cleanup there. I guess it could be argued that cleanup could also be the responsibility of unregistering party?
